# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    carre:
      filters:
        fixed:
          width: 120
          height: 90
    article:
      filters:
        watermark:
          image: ../public/image/logo-site3.png
          size: 0.1
          position: bottomright
    article1:
      quality: 100
      filters:
        upscale:
          min: [500, 500]
        thumbnail:
          size: [500, 500]
          mode: outbound
