---
#---------------------------------------route statiques-----------------------------------------------------
qui-sommes-nous:
  path: /qui-somme-nous
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "statique/quiSommesNous.html.twig"
politique-de-confidentialite:
  path: /politique-de-confidentialite
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "statique/politique-de-confidentialite.html.twig"
conditions-generales-de-vente:
  path: /conditions-generales-de-vente
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "statique/conditions-generales-de-vente.html.twig"
magasins:
  path: /magasins
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "statique/magasins.html.twig"
mentions-legales:
  path: /mentions-legales
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "statique/mentions-legales.html.twig"
